version: '3'
services:
  boxtracker_mongo:
    image: 'mongo:latest'
    restart: unless-stopped
    volumes:
      - 'mongo_data:/data/db'
    ports: 
      - 27017:27017/tcp
    command: --quiet --logpath /dev/null 
  boxtracker_api:
    image: boxtracker_api
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    ports: 
      - 8000:8000/tcp
    depends_on:
      - boxtracker_mongo
volumes:
  mongo_data:
    driver: local